# Generated by Django 4.0.6 on 2022-07-22 06:20

import app_Video_Uploader.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Video_Uploader', '0002_video_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv']), app_Video_Uploader.validators.validate_video_size]),
        ),
    ]
